# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-19 00:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True, verbose_name='Fecha')),
                ('presente', models.CharField(choices=[('Presente', 'Presente'), ('Ausente', 'Ausente')], max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cursado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField(auto_now=True, verbose_name='Fecha de Inscripción')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_finalizado', models.DateField(verbose_name='Fecha de Finalización')),
                ('cupo', models.IntegerField(verbose_name='Cupo')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('horario_cursado', models.TextField(verbose_name='Horario de cursado')),
                ('estado', models.CharField(choices=[('En Espera', 'En Espera'), ('Aceptado', 'Aceptado'), ('Terminado', 'Terminado'), ('Cancelado', 'Cancelado')], max_length=255, null=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.Docente')),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('tema_evaluacion', models.TextField(verbose_name='Temas evaluados')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Nota de la evaluación')),
                ('cursado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.Cursado')),
            ],
        ),
        migrations.AddField(
            model_name='cursado',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.Curso'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='cursado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.Cursado'),
        ),
    ]
