# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-12 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=255, verbose_name='Apellido')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('documento', models.CharField(max_length=11, unique=True, verbose_name='Número de documento')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
            ],
            options={
                'verbose_name_plural': 'Personas',
                'verbose_name': 'Persona',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personas.Persona')),
                ('nroAlumno', models.CharField(max_length=6, unique=True, verbose_name='Legajo')),
            ],
            bases=('personas.persona',),
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personas.Persona')),
                ('nroDocente', models.CharField(max_length=6, unique=True, verbose_name='Legajo')),
            ],
            bases=('personas.persona',),
        ),
    ]
